
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      CC_TEST_REPORTER_ID: 449af2ac3f6789ebb164b4033168167b504e390acada25ff7ef5d2b1f3f34e3a
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # Setup Code Climate
            - run:
                name: "Setup Code Climate Test-Reporter"
                command: |
                  # download test reporter as a static binary
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter
            # Run tests
            - run: ./cc-test-reporter before-build
            - run: npm run test-ci && ./cc-test-reporter after-build --exit-code $?
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get update && sudo apt-get install -y python-dev
            - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
            - run: sudo python get-pip.py
            - run: sudo -H pip install awscli --upgrade --ignore-installed six
            - run: npm uninstall node-sass -g && npm cache clean --force && npm install node-sass
            - run: npm run deploy
workflows:
    build-and-deploy:
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            filters:
              branches:
                only: master
